homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: '::homepage.html.twig'

smart_blog:
    resource: "@SmartBlogBundle/Resources/config/routing.yml"
    prefix:   /blog/

acme_news:
    resource: "@AcmeNewsBundle/Resources/config/routing.yml"
    prefix:   /news/

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
