homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: '::homepage.html.twig'

smart_blog:
    resource: "@SmartBlogBundle/Resources/config/routing.yml"
    prefix:   /blog/
