smart_blog_index:
    path: /
    defaults: { _controller: SmartBlogBundle:Default:index }

smart_blog_article:
    path: /{slug}/
    defaults: { _controller: SmartBlogBundle:Default:index }

smart_blog_category:
    path: /category/{slug}/
    defaults: { _controller: SmartBlogBundle:Default:index }

#smart_blog_category_page:
#    path: /category/{slug}/page{page_num}/
#    defaults: { _controller: SmartBlogBundle:Default:index }

smart_blog_tag:
    path: /tag/{slug}/
    defaults: { _controller: SmartBlogBundle:Default:index }

smart_blog_archive_yearly:
    path: /archive/{year}/
    defaults: { _controller: SmartBlogBundle:Default:index }

smart_blog_archive_monthly:
    path: /archive/{year}/{month}/
    defaults: { _controller: SmartBlogBundle:Default:index }

smart_blog_archive_dayly:
    path: /archive/{year}/{month}/{day}/
    defaults: { _controller: SmartBlogBundle:Default:index }

smart_blog_admin:
    resource: "@SmartBlogBundle/Resources/config/routing_admin.yml"
    prefix: /admin/
